[package]
name = "lator"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.27.2" }
eframe = { version = "0.27.2", features = ["default"] }
regex = "1.10.4"
lazy_static = "1.4.0"

[dev-dependencies]
rstest = "0.21.0"