[package]
name = "lator"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = { version = "0.28.1" }
eframe = { version = "0.28.1", features = ["default"] }
regex = "1.10.4"
lazy_static = "1.4.0"
thiserror = "1.0.63"

[dev-dependencies]
rstest = "0.21.0"