name: Continuous Integration

on:
  push:
    branches: [ '*' ]

jobs:
  test-on-linux:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      platform-label: ubuntu-latest

  test-on-windows:
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      platform-label: windows-latest